package ru.sea.port.model.location;

public enum LocationType {
	SHIP,
	SORTING_REGULAR,
	SORTING_REFRIGERATED,
	WAREHOUSE_REGULAR,
	WAREHOUSE_REFRIGERATED,
	WAREHOUSE_DAMAGED,
	DEPARTURE_RAIL,
	DEPARTURE_TRUCK,
	DEPARTURE_SHIP
}